Init Arrays

In [83]:
import numpy as np

# HW Data
x = np.array([0.2, -1.1, 1, 0.5, -0.6])
y = np.array([-0.3, 2, -2.2, -1, 1])

# # Example Data
# x = np.array([2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2.0, 1.0, 1.5, 1.2])
# y = np.array([2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 1.6, 1.1, 1.6, 0.9])

x_avg = x - x.mean()
y_avg = y - y.mean()

# print(0.2 + -1.1 + 1 + 0.5 + -0.6 + 0)

print("Original Inputs:")
display(x)
display(y)
print("--------------------")
print("Zeroed Inputs:")
display(x_avg)
display(y_avg)

Original Inputs:


array([ 0.2, -1.1,  1. ,  0.5, -0.6])

array([-0.3,  2. , -2.2, -1. ,  1. ])

--------------------
Zeroed Inputs:


array([ 0.2, -1.1,  1. ,  0.5, -0.6])

array([-0.2,  2.1, -2.1, -0.9,  1.1])

In [84]:
def calc_cov_matrix (x, y):
    # x_mean = x.mean()
    # y_mean = y.mean()

    # for i in x.len():
        # ((x[i] - x_mean) * (y[i] - y_mean) / (i - 1))
    
    # Turn the 2 vars into a matrix, then send them into np.cov
    return np.cov(np.stack((x, y,)))



In [85]:
cov_matrix = calc_cov_matrix(x, y)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

display(eigenvalues)
display(eigenvectors)

# sorted_indices = np.argsort(eigenvalues)
sorted_indices =  np.argsort(eigenvalues)[::-1]

display(sorted_indices)
p = 1

top_p_eigenvectors = eigenvectors[:, sorted_indices[:p]]

print(f"Top P Eigenvectors\n{top_p_eigenvectors}")
# display(top_p_eigenvectors)

# np.stack((x, y,), axis=0)

array([0.003701, 3.431299])

array([[-0.890213,  0.455545],
       [-0.455545, -0.890213]])

array([1, 0])

Top P Eigenvectors
[[ 0.455545]
 [-0.890213]]


In [86]:
# 

display(top_p_eigenvectors)
display(x_avg)

matrix_avg = np.stack((x_avg, y_avg))

display(matrix_avg)

matrix_adjusted = np.dot(matrix_avg.T, top_p_eigenvectors)

# adjusted_x = matrix_adjusted[0]
# adjusted_y = matrix_adjusted[1]

top_variance = (eigenvalues[sorted_indices[p-1]]  / (eigenvalues[sorted_indices[p-1]] + eigenvalues[sorted_indices[p-2]]) ) * 100

print(f"Ammount of variance explained by the top {p} eigenvectors: {top_variance}%")

# display(adjusted_x)
# display(adjusted_y)

np.set_printoptions(suppress=True, precision=6)


print(f"Final Input Values:\n{matrix_adjusted}")
print()


array([[ 0.455545],
       [-0.890213]])

array([ 0.2, -1.1,  1. ,  0.5, -0.6])

array([[ 0.2, -1.1,  1. ,  0.5, -0.6],
       [-0.2,  2.1, -2.1, -0.9,  1.1]])

Ammount of variance explained by the top 1 eigenvectors: 99.8922497109134%
Final Input Values:
[[ 0.269152]
 [-2.370546]
 [ 2.324992]
 [ 1.028964]
 [-1.252561]]



In [87]:
## Generated Code used for Checking my work:

from sklearn.decomposition import PCA
import numpy as np

# Your original data matrix with shape (n_samples, n_features)
X = np.column_stack([x, y])  # example if you have variables x and y

k = 1  # Number of principal components to keep

pca = PCA(n_components=k)
pca.fit(X)

# Principal components (eigenvectors)
print("Components:\n", pca.components_)

# Explained variance (eigenvalues)
print("Explained Variance:\n", pca.explained_variance_)

# Mean of features (used for centering)
print("Mean:\n", pca.mean_)

# Transform the data into principal component space
X_pca = pca.transform(X)
print("Projected Data:\n", X_pca)


Components:
 [[-0.455545  0.890213]]
Explained Variance:
 [3.431299]
Mean:
 [-0.  -0.1]
Projected Data:
 [[-0.269152]
 [ 2.370546]
 [-2.324992]
 [-1.028964]
 [ 1.252561]]
